version: '3.9'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    command: bash -c
        "
        alembic upgrade head
        && uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
        "
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    depends_on:
      - server


volumes:
  postgres_data:
