"""Created users model

Revision ID: e50345862256
Revises: 6a15d16a96e9
Create Date: 2022-03-10 21:55:12.536850

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e50345862256"
down_revision = "6a15d16a96e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "another_one")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("another_one", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
