"""Updated items model

Revision ID: 2033669a7c5c
Revises: d83318068f5f
Create Date: 2022-03-09 14:19:37.359415

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2033669a7c5c"
down_revision = "d83318068f5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("slug", sa.String(length=80), nullable=True))
    op.add_column("items", sa.Column("cost", sa.Float(), nullable=False))
    op.add_column("items", sa.Column("price", sa.Float(), nullable=False))
    op.add_column("items", sa.Column("discount", sa.Float(), nullable=True))
    op.add_column("items", sa.Column("inventory", sa.Float(), nullable=False))
    op.add_column("items", sa.Column("available", sa.Boolean(), nullable=True))
    op.add_column(
        "items",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "created_at")
    op.drop_column("items", "available")
    op.drop_column("items", "inventory")
    op.drop_column("items", "discount")
    op.drop_column("items", "price")
    op.drop_column("items", "cost")
    op.drop_column("items", "slug")
    # ### end Alembic commands ###
