"""Added product model

Revision ID: 1a7d56ed86bd
Revises:
Create Date: 2022-03-09 00:21:48.162702

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1a7d56ed86bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
