"""Added slug to product model

Revision ID: 5a969df6395a
Revises: fea22fc49f49
Create Date: 2022-03-09 00:24:21.909492

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5a969df6395a"
down_revision = "fea22fc49f49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("slug", sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "slug")
    # ### end Alembic commands ###
