"""Created users model

Revision ID: 6a15d16a96e9
Revises: c328d77c7f97
Create Date: 2022-03-10 21:54:52.743279

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6a15d16a96e9"
down_revision = "c328d77c7f97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("another_one", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "another_one")
    # ### end Alembic commands ###
